### ISSUE TITLE
update-config.sh Error

### ISSUE THREAD

**Issue by harryabbott** [AdrienPoupa/docker-compose-nas#70] opened 2024-05-07 10:24 UTC
Hi, 

running `./update-config.sh` while the stack is running (for the first time) gives me this error:

```./update-config.sh: line 6: Updating ${container^} configuration...: bad substitution```

I do not have any API keys set in the .env (as i assume this script populates them?) 

I'm having some other issues getting the stack started too, which may or may not be related so i will dump them here. I am happy to spin them off into their own issues if you see fit. 

- Unpackerr gets stuck restarting with the error ```provided application API Key is invalid, must be 32 characters, your key length: 0``` since the key will not be set by the sh script.
- Jellyfin gets stuck on "created" while the rest of the containers say "running", i fixed this by commenting out services.jellyfin.devices on the docker-compiose.yml after the below error
- after the compose runs, i get this error: ```Error response from daemon: error gathering device information while adding custom device "/dev/dri/renderD128": no such file or directory``` (fixed by above)
- `dependency failed to start: container vpn is unhealthy` after compose
- vpn container erroring out - <img width="913" alt="image" src="https://github.com/AdrienPoupa/docker-compose-nas/assets/53835143/abcfb879-4170-4b64-83da-8d9d346ef57f">

also, how to I access the jellyfin UI? or jellyseerr/sonarr/radarr, or any of the other services? 

Thanks, 
Harry

**Comment by harryabbott** [comment] 2024-05-07 10:52
i went through the config.xml for sonarr radarr  prowlarr manually and populated the api keys, 
figured out how to access, for some reason http://localhost:8080/jellyfin didnt work, but http://localhost/jellyfin did. 

but now jellyfin gives me this error in webUI:
`Application error: a client-side exception has occurred (see the browser console for more information).`

![image](https://github.com/AdrienPoupa/docker-compose-nas/assets/53835143/8c904d02-cf37-4c36-aa9d-52364bc991d3)

I havent got the jellyfin api key set, since i cant find it in the files, anywhere under /config/.

**Comment by chri1852** [comment] 2024-05-12 20:24
I am also now getting the same error as @harryabbott . I hadn't changed anything with the setup recently, and all the other parts seem to be working just fine, so It is just an issue with JellyFin I suspect. I tried the classic turn it off an on again, to no avail. I am planning to find some time during this week to take a more in depth crack at it. If I find a fix I'll post it here.

**Comment by AdrienPoupa** [comment] 2024-05-13 03:45
Hi Harry! Sorry you had all of those issues.

> ./update-config.sh: line 6: Updating ${container^} configuration...: bad substitution

I think you may be using Bash 4? The upper case operator (`^` and `^^`) was added in Bash 5. I modified the script to make it work with older versions.

> I do not have any API keys set in the .env (as i assume this script populates them?)

Correct, when the script finishes your `.env` will be filled up (except for Jellyfin, you have to create an API key in the panel as mentioned in the readme)

> Unpackerr gets stuck restarting with the error provided application API Key is invalid, must be 32 characters, your key length: 0 since the key will not be set by the sh script.

Indeed, it needs the API keys in the `.env` to connect to Radarr and Sonarr.

> Jellyfin gets stuck on "created" while the rest of the containers say "running", i fixed this by commenting out services.jellyfin.devices on the docker-compiose.yml after the below error

Good call, I removed those two bind mounts given they're not present in all installations and updated the readme.

> dependency failed to start: container vpn is unhealthy after compose
> vpn container erroring out - 

I could not reproduce this one, the VPN started right away after I filled my credentials. Maybe double check your credentials, or report the issue upstream? https://github.com/thrnz/docker-wireguard-pia

> also, how to I access the jellyfin UI? or jellyseerr/sonarr/radarr, or any of the other services?

Jellyfin is accessible at `yourhostname/jellyfin`. Now for the tricky part, as I recreated the stack from the start, I realized that for some reason, `network.xml` was not created, probably because of this: https://github.com/jellyfin/jellyfin/issues/11548 Because it was missing it, the base URL could not be set, and Jellyfin was not responding at `/jellyfin`.

Can you maybe retry now with the latest changes? Thanks!

**Comment by chri1852** [comment] 2024-05-15 01:41
I reset that network.xml and it got it back working again. Thanks

**Comment by AdrienPoupa** [comment] 2024-05-15 14:30
Closing this, please let me know if something else is not working thanks!

**Closed by AdrienPoupa** 2024-05-15 14:30 UTC
